histogram
sfbrigade/datasci-SF-Environment-Benchmark pull request #18
Opened 2017-02-20 02:15 UTC by thfield

histogram gets data from api call

2017-02-22 02:33 UTC, eayoungs commented
Hey, I'm not getting the server to run. I followed the instructions @ https://help.github.com/articles/checking-out-pull-requests-locally/ and successfully merged locally.
I couldn't find a link in the main index, so I tried this: `http://0.0.0.0:8000/individual/index.html` but it's blank for me.

2017-02-22 02:36 UTC, thfield commented
I would try `http://localhost/individual/...` maybe? There are some vague instructions in the main readme, I'm not sure if you knew about those

2017-02-22 03:35 UTC, smoningi commented
localhost:8000/individual/index.html should work. Run python -m
SimpleHTTPServer in terminal in the main directory.

On Tue, Feb 21, 2017 at 6:36 PM, Tyler Field <notifications@github.com>
wrote:

> I would try http://localhost/individual/... maybe? There are some vague
> instructions in the main readme, I'm not sure if you knew about those
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/pull/18#issuecomment-281550616>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACAiYCj41BHdfQqmycxltr9HUD0pKI6dks5re59EgaJpZM4MFsgG>
> .
>

2017-03-17 02:01 UTC, eayoungs requested changes
Looks like the **data/75rg-imyz.json** doesn't seem to be used in **test.js**. It seems to still be referencing `../data/j2j3-acqj.json`.
I like the page and it seems to run fine at _http://localhost:8000/dashboard/test.html_ but the data doesn't seem to load. Also, the "**Building Type:**" dropdown doesn't seem to be populated.

2017-03-17 16:52 UTC, eayoungs commented on individual/individual.js
> -const DATASOURCE = 'j2j3-acqj' // ? '75rg-imyz'
Something is wrong with the data here; does not appear to be loading properly

2017-03-18 01:33 UTC, eayoungs commented on dashboard/dashboard.js
> +      .defer(d3.json, "../data/j2j3-acqj.json") //this data has already loaded at this point, why is it doing it agian? /* https://data.sfgov.org/resource/j2j3-acqj.json?$limit=2000 */
I looked into this. Not sure but seems to go back some ways, at least to September 2016

2017-03-18 16:21 UTC, thfield commented on individual/individual.js
> -const DATASOURCE = 'j2j3-acqj' // ? '75rg-imyz'
i think the data source needs to be switched for that soda-js to work properly, not sure why this slipped by.  'j2j3' should be switched for '75rg'.  i think soda-js wants the soda api v2 and 'j2j3' is served through soda api v1.

2017-03-18 16:22 UTC, thfield commented
test.js/test.html probably shouldn't have gotten added to the commit, i wouldn't worry about anything going on in them.

2017-03-18 16:34 UTC, thfield commented on individual/individual.js
> -const DATASOURCE = 'j2j3-acqj' // ? '75rg-imyz'
yup, looks like i switched it in a commit that i had forgotten to push

2017-03-18 22:46 UTC, eayoungs approved these changes

2017-03-18 23:09 UTC, merged