Added new html and css for the building dashboard page
sfbrigade/datasci-SF-Environment-Benchmark pull request #25
Opened 2017-03-14 07:12 UTC by askiefer

Hey both, wanted to go ahead and push the new html / css for the latest mockups, https://projects.invisionapp.com/share/2SAI4AK48#/screens/221959111.

Although I'm srcing in the javascript chart files the charts are returning js console errors (ts tsk on my part I know). 

This does not include the building data at all (I hardcoded one in) but I wanted to provide the html for the layout at the very least.

2017-03-15 22:25 UTC, eayoungs commented
Looks good @askiefer ! I don't see the 'donut', should I assume that's coming?

Also, a minor issue, but I don't see a link to `building_dashboard.html` in the main `index.html` file. This is the landing page that opens when you run _SimpleHTTPServer_ (which is *http.server* in Python3, BTW).
LMK whether or not you want to change either of these things and I'll be happy to merge this PR.

2017-03-15 22:27 UTC, eayoungs approved these changes
- Didn't see the _donut_ chart.
- [x] Might want to add a link to `building_dashboard.html` in the root `index.html` file for easy access

2017-03-15 23:07 UTC, thfield requested changes
looks great!
let's get together a list of the all dynamic elements and give them ids so we can get this using real data!

2017-03-15 23:07 UTC, thfield commented on dashboard/building_dashboard.html
> +		                			<a href="/https://sfenvironment.org/energy/energy-efficiency/commercial-and-multifamily-properties/existing-commercial-buildings-energy-performance-ordinance">What is the Existin
`<a href="https://sfenvironment.org/energy/ ...`

2017-03-15 23:07 UTC, thfield commented on dashboard/building_dashboard.html
> +		                			<a href="/https://sfenvironment.org/sites/default/files/fliers/files/sfe_gb_ecb_benchmark_instructions.pdf">How to submit benchmarking data</a>
`<a href="https://sfenvironment.org/sites ...`

2017-03-15 23:07 UTC, thfield commented on dashboard/building_dashboard.html
> +		            			<a href="/https://sfenvironment.org/article/commercial/sf-energy-watch-commercial-program">San Francisco Energy Watch can help you save money, save energy, and improve your ENERGY ST
`<a href="https://sfenvironment.org/article/commercial/sf-en`

2017-03-15 23:07 UTC, thfield commented on dashboard/building_dashboard.html
> +	                			<button type="button" class="btn btn-primary btn-round-lg btn-lg">SUBMIT NOW</button>
should the button be a `<a href="http://sfenvironment.org/submit" class="btn btn-primary ...` instead, so clicking goes somewhere?

2017-03-15 23:14 UTC, thfield commented
ps. this past week i wired up a c3 ringchart in my branch that's a part of #18, so i think we're in pretty good shape.  just a matter of connecting the pieces now

2017-03-15 23:15 UTC, thfield commented on dashboard/building_dashboard.html
> +	                			<button type="button" class="btn btn-primary btn-round-lg btn-lg">SUBMIT NOW</button>
this one isn't a "required" change, just something to think about

2017-03-16 02:53 UTC, askiefer commented
@eayoungs Yes totally, will do! And yes the donut chart is to come. I'll see if I can add it.

And yes thanks @tyler - totally! Will add.

2017-03-16 03:18 UTC, askiefer commented
Also I might incorporate the latest mockup changes in this PR - shouldn't be a lot but just an FYI

2017-03-16 03:53 UTC, thfield approved these changes

2017-03-18 23:35 UTC, eayoungs requested changes
I'm not seeing any of the individual charts that I thought were added. I noticed some errors in the console and found the change below eliminated several related to jQuery.
There are a few more errors related to attributes in the page having NaN values. I think it might be best to close this PR and tackle this with some further work, especially since @thfield is relying on these changes in the next PR.

2017-03-18 23:35 UTC, eayoungs commented on dashboard/building_dashboard.html
> +	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
I was getting some errors in the console about jquery not found but fixed them by adding this line here:
`<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>`

2017-03-19 18:05 UTC, thfield commented on dashboard/building_dashboard.html
> +	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
there are a couple repeated js libraries and a couple that are for maps which aren't being used.  i pared them down at some point in #27

2017-03-19 18:10 UTC, thfield commented
i don't think the charts actually get implemented in this PR, i'm about to tackle the GHG histogram, and i think that @askiefer got the barchart working locally?

2017-03-20 22:49 UTC, eayoungs approved these changes

2017-03-20 22:52 UTC, eayoungs commented
Looks good. I see charts on _ENERGY STAR SCORE_ and _SITE ENERGY USE INTENSITY_.

2017-03-20 22:52 UTC, merged